# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Language and timezone settings
lang: en
timezone: Asia/Seoul

# SEO and site information
title: Rachel.com
tagline: Rachel's Dev Log
description: >-
  Rachel's Dev Log.
url: "https://Rachel-3.github.io"
#
# Social media and contact information
github:
  username: Rachel-3

instagram:
  username: chae.rim_e

social:
  name: Chae-rim Yoon
  email: cofla226@naver.com
  links:
    - https://instagram.com/chae.rim_e
    - https://github.com/Rachel-3

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings
analytics:
  google:
    id: G-W6P15Q2JVX
  goatcounter:
    id: rachel
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:

# Pageviews settings
pageviews:
  provider: google

# Theme mode (light/dark)
theme_mode:

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, posts' images, audio and video files) paths starting with '/'
#
# e.g. 'https://cdn.com'
# cdn: "https://chirpy-img.netlify.app"

# Avatar setting
avatar: "/assets/img/profile/profile.jpg"

# Social preview image (Optional: Add if using)
social_preview_image:

# Table of Contents
toc: true

# Comments settings
comments:
  provider: giscus
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo: Rachel-3/Rachel-3.github.io
    repo_id: R_kgDOMDjSrA
    category: Q&A
    category_id: DIC_kwDOMDjSrM4CfyHL
    mapping: pathname
    strict: 0
    input_position: bottom
    lang: en
    reactions_enabled: 1

# Self-hosted static assets settings (Optional: Add if using)
assets:
  self_host:
    enabled:
    env:

# PWA settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# Pagination
paginate: 10

# Base URL
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
